"""Pinned content catalog and user-level installer."""

from functools import lru_cache

from .install import (
    AcquisitionRequired,
    Installer,
    InstallError,
    download,
    safe_extract_tar,
    safe_extract_zip,
    sha256_file,
    verify_git_checkout,
)
from .model import (
    ActionSpec,
    AssetFileSpec,
    AssetLicenseSpec,
    AssetSpec,
    Catalog,
    CatalogError,
    ContentSpec,
    LifecycleSpec,
    PackageSpec,
)
from .receipt import (
    BindingMismatch,
    DecisionDeclined,
    DecisionInvalid,
    DurabilityUnknown,
    LicenseDecision,
    ReceiptError,
    ReceiptMissing,
    ReceiptStore,
    ReconcileResult,
    RecordResult,
    ReleaseContext,
    StoreBusy,
    StoredReceiptInvalid,
    UnsafeStore,
    VerifiedInput,
    VerifiedReceipt,
    verified_packaged_catalog,
)
from .u1 import (
    PackagedReleaseCapability,
    U1ContractError,
    U1_LICENSE_NAME,
    U1_MANIFEST_NAME,
    U1_MANIFEST_SHA256,
    U1_SCHEMA_NAMES,
    ValidatedU1Record,
    canonical_json_bytes,
    packaged_release_capability,
    packaged_resource_bytes,
    packaged_u1_hashes,
    parse_json_bytes,
    production_capacity_policy_available,
    validate_u1_bytes,
    verify_packaged_u1_resources,
    verify_packaged_u1_manifest,
)
from .u1_core import (
    authorization_record_digest,
    capacity_generation_digest,
    capacity_policy_digest,
    catalog_digest,
    filesystem_key_bytes,
    filesystem_key_digest,
    install_authority_digest,
    install_record_digest,
    output_binding_digest,
    release_proof_digest,
    retention_accounted_digest,
    retention_absence_evidence_digest,
    retention_component_digest,
    retention_component_envelope_digest,
    retention_descriptor_digest,
    retention_envelope_digest,
    retention_handoff_digest,
    retention_intent_digest,
    retention_logical_state_digest,
    retention_marker_content_digest,
    retention_marker_digest,
    retention_marker_semantic_bytes,
    retention_marker_semantic_digest,
    retention_physical_envelope_digest,
    retention_physical_state_digest,
    retention_relation_content_digest,
    retention_relation_digest,
    retention_relation_semantic_bytes,
    retention_relation_semantic_digest,
    source_identity_digest,
    transaction_generation_digest,
)

__version__ = "0.4.0"


@lru_cache(maxsize=1)
def default_catalog() -> Catalog:
    """Return the packaged catalog after verifying its exact frozen bytes."""
    return verified_packaged_catalog()


__all__ = [
    "AcquisitionRequired",
    "ActionSpec",
    "AssetFileSpec",
    "AssetLicenseSpec",
    "AssetSpec",
    "BindingMismatch",
    "Catalog",
    "CatalogError",
    "ContentSpec",
    "DecisionDeclined",
    "DecisionInvalid",
    "DurabilityUnknown",
    "InstallError",
    "Installer",
    "LicenseDecision",
    "LifecycleSpec",
    "PackageSpec",
    "ReceiptError",
    "ReceiptMissing",
    "ReceiptStore",
    "ReconcileResult",
    "RecordResult",
    "ReleaseContext",
    "StoreBusy",
    "StoredReceiptInvalid",
    "UnsafeStore",
    "VerifiedInput",
    "VerifiedReceipt",
    "verified_packaged_catalog",
    "default_catalog",
    "download",
    "safe_extract_tar",
    "safe_extract_zip",
    "sha256_file",
    "verify_git_checkout",
    "U1ContractError",
    "PackagedReleaseCapability",
    "U1_LICENSE_NAME",
    "U1_MANIFEST_NAME",
    "U1_MANIFEST_SHA256",
    "U1_SCHEMA_NAMES",
    "ValidatedU1Record",
    "authorization_record_digest",
    "capacity_generation_digest",
    "capacity_policy_digest",
    "catalog_digest",
    "canonical_json_bytes",
    "filesystem_key_bytes",
    "filesystem_key_digest",
    "install_authority_digest",
    "install_record_digest",
    "output_binding_digest",
    "packaged_release_capability",
    "packaged_resource_bytes",
    "packaged_u1_hashes",
    "parse_json_bytes",
    "production_capacity_policy_available",
    "release_proof_digest",
    "retention_accounted_digest",
    "retention_absence_evidence_digest",
    "retention_component_digest",
    "retention_component_envelope_digest",
    "retention_descriptor_digest",
    "retention_envelope_digest",
    "retention_handoff_digest",
    "retention_intent_digest",
    "retention_logical_state_digest",
    "retention_marker_content_digest",
    "retention_marker_digest",
    "retention_marker_semantic_bytes",
    "retention_marker_semantic_digest",
    "retention_physical_envelope_digest",
    "retention_physical_state_digest",
    "retention_relation_content_digest",
    "retention_relation_digest",
    "retention_relation_semantic_bytes",
    "retention_relation_semantic_digest",
    "source_identity_digest",
    "transaction_generation_digest",
    "validate_u1_bytes",
    "verify_packaged_u1_resources",
    "verify_packaged_u1_manifest",
]
