#!/usr/bin/env python3
"""Derive tools/upstream-pins/encodec-*.json from kilix-encodec (R4-068, C4-VERIFY F6).

C4-IMPL said the two EnCodec pins were generated by a script that reads
kilix-encodec's own `tools/converter-inputs.json` and `python/graph_population.py`
and cross-checks them. That script was not committed, so the pins were not
re-derivable from this repository. This is that script, committed.

It reads the other repository with `git show <ref>:<path>` only -- never a
checkout, never a network fetch, never a model byte. Two sources state the same
population, and it requires them to agree before it writes anything:

  tools/converter-inputs.json  the converter's own input/output pins
  python/graph_population.py   the native consumer's installed-graph identity

What is DERIVED from kilix-encodec: the converter's input URLs, byte counts and
digests; the produced population; the asset version; the converter command
names; and, when the profile records one, the measured `temporary_bytes` for
the conversion's peak scratch (see `measured_temporary_bytes`). What is
AUTHORED here, because it is kilix-content's side of the contract and appears
nowhere upstream: the installed converter path, the per-profile timeout, the
catalogue ids, labels, provider, stream, consumer schema, licence record id,
and the provenance project.

Guards, in the order they run:

* both sources must list exactly the same population (path, bytes, sha256);
* the version must be the one the native consumer requires, and must end in the
  first eight hex characters of the manifest digest, so a population cannot be
  swapped without the version moving with it;
* the manifest digest must equal the accepted one named below. This is what
  keeps a superseded population out, and it does so positively: a refusal list
  of superseded digests would have to carry them as literals, and this file is
  scanned by tests/test_c4_encodec_records.py for exactly that;
* the native consumer's installed-bytes budget must cover the population;
* a measured `temporary_bytes` must be a byte count no smaller than the inputs
  and outputs it claims to have measured;
* the rendered pin may contain no 64-hex string that is not one of the digests
  derived above, so a stand-in digest cannot be smuggled into a pin;
* every derived digest and byte count must survive a round trip through the
  renderer unchanged.

Usage:
    tools/generate_encodec_pins.py --repo PATH [--ref REF] --check   (default)
    tools/generate_encodec_pins.py --repo PATH [--ref REF] --write
"""

from __future__ import annotations

import argparse
import ast
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PIN_DIR = ROOT / "tools" / "upstream-pins"

# The kilix-encodec release line E1-RV-VERIFY accepted (R4-067 re-pins it).
DEFAULT_REF = "16ad64ce545bd2abb5531439b9bf1b1c28c76767"

CONVERTER_INPUTS = "tools/converter-inputs.json"
GRAPH_POPULATION = "python/graph_population.py"

_HEX64 = re.compile(r"\b[0-9a-f]{64}\b")

# The accepted populations (SR-1, SR-3, SR-5, SR-10), by manifest digest.
ACCEPTED_MANIFEST = {
    "encodec-24khz-stateful": (
        "bb615145d4a33dbfa4c07c1ff3283303b461af1c6fc83dbf50b59bcf6489f81b"
    ),
    "encodec-48khz-frame": (
        "2ce5225dc458dd30fe91854755dcfb360300fe3cee7d0c5682e7be684eae7a87"
    ),
}

# kilix-content's side of the contract. None of this exists upstream.
PROFILES = {
    "24khz": {
        "id": "encodec-24khz-stateful",
        "label": "EnCodec 24 kHz stateful graphs",
        "license_record_id": "encodec-24khz-stateful",
        "primary_input": "encodec_24khz-d7cc33bc.th",
        "install_primary_as": None,  # a single file: no input directory
        "project": "facebookresearch/encodec",
        "timeout": "180",
        "tool_asset_id": "kilix-encodec-convert-24khz",
    },
    "48khz": {
        "id": "encodec-48khz-frame",
        "label": "EnCodec 48 kHz frame graphs",
        "license_record_id": "encodec-48khz-frame",
        "primary_input": "model.safetensors",
        "install_primary_as": "model.safetensors",
        "project": "facebook/encodec_48khz",
        "timeout": "300",
        "tool_asset_id": "kilix-encodec-convert-48khz",
    },
}

CONVERTER_ROOT = "/usr/lib/plebian-os/kilix-encodec/bin"
PROVIDER = "kilix-encodec"
CONSUMER_SCHEMA = "kilix.encodec.graphs/v1"
STREAM = "F101"
PIN_SCHEMA = "kilix.content.upstream-pin/v1"


class PinError(Exception):
    pass


def show(repo: str, ref: str, path: str) -> bytes:
    completed = subprocess.run(
        ["git", "-C", repo, "--no-optional-locks", "show", f"{ref}:{path}"],
        capture_output=True,
    )
    if completed.returncode != 0:
        raise PinError(
            f"git show {ref}:{path} in {repo} exited {completed.returncode}: "
            f"{completed.stderr.decode('utf-8', 'replace').strip()}"
        )
    return completed.stdout


def population_from_module(source: bytes) -> dict[str, tuple[str, int, dict]]:
    """PROFILES from python/graph_population.py, read as data, never imported."""
    tree = ast.parse(source.decode("utf-8"), filename=GRAPH_POPULATION)
    assigned = [
        node
        for node in tree.body
        if isinstance(node, ast.Assign)
        and len(node.targets) == 1
        and isinstance(node.targets[0], ast.Name)
        and node.targets[0].id == "PROFILES"
    ]
    if len(assigned) != 1:
        raise PinError(
            f"{GRAPH_POPULATION} binds PROFILES {len(assigned)} times; expected 1"
        )
    profiles = ast.literal_eval(assigned[0].value)
    found: dict[str, tuple[str, int, dict]] = {}
    for asset_id, version, budget, population in profiles.values():
        found[asset_id] = (
            version,
            budget,
            {
                path: {"bytes": size, "sha256": digest}
                for path, size, digest in population
            },
        )
    return found


def measured_temporary_bytes(
    asset_id: str,
    profile: dict,
    inputs: dict,
    primary: dict,
    extra: list[str],
    installed: int,
) -> int | None:
    """An upstream measurement of the conversion's peak scratch, or None.

    C4-VERIFY F5 replaced an underived 4 GiB with a derived floor -- the
    fetched inputs and the produced outputs, which are on disk together -- and
    C4-FIX-VERIFY V-F2 then found that the documented way to raise it could not
    be executed: `sizes.temporary_bytes` in the record comes from the pin's
    optional `temporary_bytes`, this generator never emitted that key, and
    `test_the_fixture_reproduces_the_committed_pins` rebuilds the pin from
    upstream and refuses anything the generator would not have written. So a
    hand-added override -- including a legitimate measured one -- failed the
    suite.

    It is emitted here instead, which keeps both properties: a value above the
    floor must cite a measurement recorded upstream, and the pin still
    reproduces byte for byte from kilix-encodec.

    **How a future conversion sets it.** Run the real converter once, measure
    the peak bytes resident in the install scratch over the run (inputs,
    outputs and the converter's own working set), and record that number in
    kilix-encodec's `tools/converter-inputs.json`, in the profile, as
    `temporary_bytes`. Then, in this repository:

        tools/generate_encodec_pins.py --repo <kilix-encodec> --ref <ref> --write
        PYTHONPATH=... tools/generate_upstream_records.py --old <current _CATALOG_SHA256>
        make test

    Nothing is hand-edited at any step, and `make pins` re-derives all of it.

    The floor checked here is what this generator can derive from upstream:
    the inputs plus the produced population. The record's own floor is that
    plus the licence notice files, which only the record generator knows, and
    `build_convert_asset` refuses an override below it -- so a value in the
    narrow band between the two is refused there, by name, rather than
    becoming a record the suite fails on.
    """
    value = profile.get("temporary_bytes")
    if value is None:
        return None
    if type(value) is not int or value < 0 or value > 2**63 - 1:
        raise PinError(
            f"{asset_id}: {CONVERTER_INPUTS} temporary_bytes must be a "
            f"non-negative 64-bit integer, not {value!r}"
        )
    download = int(primary["bytes"]) + sum(int(inputs[name]["bytes"]) for name in extra)
    floor = download + installed
    if value < floor:
        raise PinError(
            f"{asset_id}: measured temporary_bytes {value} is below the "
            f"{floor} bytes the conversion's own inputs and outputs occupy "
            f"together; a measurement cannot be smaller than what it measured"
        )
    return value


def build_pin(name: str, profile: dict, native: tuple[str, int, dict]) -> dict:
    authored = PROFILES[name]
    asset_id = authored["id"]
    version, budget, native_population = native

    outputs = {
        path: {"bytes": item["bytes"], "sha256": item["sha256"]}
        for path, item in profile["outputs"].items()
    }
    if outputs != native_population:
        differing = sorted(
            set(outputs) ^ set(native_population)
            | {
                path
                for path in set(outputs) & set(native_population)
                if outputs[path] != native_population[path]
            }
        )
        raise PinError(
            f"{asset_id}: {CONVERTER_INPUTS} and {GRAPH_POPULATION} disagree "
            f"about {differing}"
        )
    manifest = outputs["manifest.json"]["sha256"]
    if manifest != ACCEPTED_MANIFEST[asset_id]:
        raise PinError(
            f"{asset_id}: manifest digest {manifest} is not the accepted "
            f"population {ACCEPTED_MANIFEST[asset_id]}"
        )
    if not version.endswith(manifest[:8]):
        raise PinError(
            f"{asset_id}: version {version!r} does not end in the manifest's "
            f"first eight hex characters ({manifest[:8]})"
        )
    installed = sum(item["bytes"] for item in outputs.values())
    if installed > budget:
        raise PinError(
            f"{asset_id}: population is {installed} bytes, over the native "
            f"consumer's budget of {budget}"
        )

    inputs = profile["inputs"]
    primary_name = authored["primary_input"]
    if primary_name not in inputs:
        raise PinError(f"{asset_id}: {primary_name} is not a converter input")
    primary = inputs[primary_name]
    primary_pin = {
        "url": primary["url"],
        "bytes": primary["bytes"],
        "sha256": primary["sha256"],
    }
    if authored["install_primary_as"] is not None:
        primary_pin["path"] = authored["install_primary_as"]

    extra = sorted(name for name in inputs if name != primary_name)
    measured = measured_temporary_bytes(asset_id, profile, inputs, primary, extra, installed)
    revision = profile.get("revision")
    if revision is None:
        # A single-file checkpoint pins itself: the file name is the revision.
        revision = primary_name.rsplit(".", 1)[0]
    if revision not in primary["url"] and not primary["url"].endswith(primary_name):
        raise PinError(f"{asset_id}: {revision} is not named by the input URL")

    pin = {
        "schema": PIN_SCHEMA,
        "id": asset_id,
        "label": authored["label"],
        "mode": "upstream-convert",
        "license_record_id": authored["license_record_id"],
        "provider": PROVIDER,
        "consumer_schema": CONSUMER_SCHEMA,
        "stream": STREAM,
        "version": version,
        "provenance": {
            "project": authored["project"],
            "revision": revision,
            "original_url": primary["url"],
        },
        "input": primary_pin,
        "outputs": [
            {"path": path, "bytes": outputs[path]["bytes"], "sha256": outputs[path]["sha256"]}
            for path in sorted(outputs)
        ],
        "conversion": {
            "tool_asset_id": authored["tool_asset_id"],
            "argv": [
                f"{CONVERTER_ROOT}/{profile['command']}",
                "--input",
                "{input}",
                "--output",
                "{output}",
                "--receipt-store",
                "{receipt_store}",
                "--manifest-digest",
                "{manifest_digest}",
                "--timeout",
                authored["timeout"],
            ],
        },
    }
    if profile["command"] != authored["tool_asset_id"]:
        raise PinError(
            f"{asset_id}: converter command {profile['command']!r} is not the "
            f"tool asset id {authored['tool_asset_id']!r}"
        )
    if extra:
        pin["inputs"] = [
            {
                "path": path,
                "url": inputs[path]["url"],
                "bytes": inputs[path]["bytes"],
                "sha256": inputs[path]["sha256"],
            }
            for path in extra
        ]
    if measured is not None:
        pin["temporary_bytes"] = measured
    return pin


def render(pin: dict) -> str:
    return json.dumps(pin, indent=2, ensure_ascii=False) + "\n"


def check_no_stand_in(pin: dict, text: str) -> None:
    """No 64-hex string may appear that is not one of the derived digests."""
    derived = {item["sha256"] for item in pin["outputs"]}
    derived.add(pin["input"]["sha256"])
    derived.update(item["sha256"] for item in pin.get("inputs", []))
    strays = sorted(set(_HEX64.findall(text)) - derived)
    if strays:
        raise PinError(f"{pin['id']}: rendered pin holds unpinned 64-hex {strays}")


def generate(repo: str, ref: str) -> dict[str, str]:
    inputs = json.loads(show(repo, ref, CONVERTER_INPUTS).decode("utf-8"))
    native = population_from_module(show(repo, ref, GRAPH_POPULATION))
    rendered: dict[str, str] = {}
    for name, profile in sorted(inputs["profiles"].items()):
        if name not in PROFILES:
            raise PinError(f"{CONVERTER_INPUTS} names an unknown profile {name!r}")
        asset_id = PROFILES[name]["id"]
        if asset_id not in native:
            raise PinError(f"{GRAPH_POPULATION} has no population for {asset_id}")
        pin = build_pin(name, profile, native[asset_id])
        text = render(pin)
        check_no_stand_in(pin, text)
        if json.loads(text) != pin:
            raise PinError(f"{asset_id}: the rendered pin does not round-trip")
        rendered[asset_id] = text
    missing = sorted({profile["id"] for profile in PROFILES.values()} - set(rendered))
    if missing:
        raise PinError(f"{CONVERTER_INPUTS} has no profile for {missing}")
    return rendered


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    parser.add_argument("--repo", required=True, help="a kilix-encodec repository")
    parser.add_argument("--ref", default=DEFAULT_REF)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    args = parser.parse_args(argv[1:])
    try:
        rendered = generate(args.repo, args.ref)
    except PinError as error:
        print(f"encodec pins: {error}", file=sys.stderr)
        return 1
    status = 0
    for asset_id, text in sorted(rendered.items()):
        path = PIN_DIR / f"{asset_id}.json"
        if args.write:
            path.write_text(text, encoding="utf-8")
            print(f"wrote {path.relative_to(ROOT)}")
            continue
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == text:
            print(f"{path.relative_to(ROOT)} matches {args.ref}")
        else:
            print(
                f"{path.relative_to(ROOT)} DIFFERS from {args.ref}",
                file=sys.stderr,
            )
            status = 1
    return status


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
