#!/usr/bin/env python3
"""Regenerate tests/data/catalog_digests.txt from the packaged catalog."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "src" / "kilix_content" / "catalog" / "plebian.json"
SOURCE = ROOT / "tests" / "data" / "catalog_source.json"
OUTPUT = ROOT / "tests" / "data" / "catalog_digests.txt"
SCHEMA = "kilix.content.catalog-digest-source/v1"
_HEX = frozenset("0123456789abcdef")


def sha256_hex(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def members_from_catalog(catalog: dict) -> list[str]:
    digests: list[str] = []
    for asset in catalog.get("assets", []):
        source = asset.get("source") or {}
        if source.get("archive_sha256"):
            digests.append(source["archive_sha256"])
        for item in asset.get("files") or []:
            digest = item.get("sha256")
            if digest:
                digests.append(digest)
    return sorted(set(digests))


def render(source_bytes: bytes, digests: list[str]) -> str:
    lines = [
        "# kilix-content catalog digest list",
        "# Generated by tools/regenerate_catalog_digests.py. Do not hand-edit.",
        "# source: tests/data/catalog_source.json",
        f"# source_sha256: {sha256_hex(source_bytes)}",
        f"# count: {len(digests)}",
    ]
    lines.extend(digests)
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    catalog = json.loads(CATALOG.read_text(encoding="utf-8"))
    digests = members_from_catalog(catalog)
    source = {
        "schema": SCHEMA,
        "members": digests,
    }
    source_bytes = (json.dumps(source, indent=2) + "\n").encode("utf-8")
    text = render(source_bytes, digests)
    if argv[1:] == ["--stdout"]:
        sys.stdout.write(text)
        return 0
    SOURCE.parent.mkdir(parents=True, exist_ok=True)
    SOURCE.write_bytes(source_bytes)
    OUTPUT.write_text(text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
